.\" Written by Kurt Lust, kurt.lust@uantwerpen.be.
.TH man 1 "17 June 2021" "1.1" "eat_cpu (vsc-tutorial) command"

.SH NAME
eat_disk \- Single-threaded program that just puts some load on the file scratch system

.SH DESCRIPTION
eat_disk is a simple single-threaded program that puts some load on the
scratch file system by generating a fairly large text file test.txt
(roughly 5 GiB) in the VSC_SCRATCH directory of the user.

The program is part of the VSC tutorial, chapter 11.

.SH SEE ALSO
vsc-tutorial(1), eat_mem(1), eat_cpu(1)

.SH AUTHOR
Kurt Lust (Kurt.Lust@uantwerpen.be)
