.\" Written by Kurt Lust, kurt.lust@uantwerpen.be.
.TH man 1 "13 July 2021" "1.2" "mpi_omp_hello (vsc-tutorial) command"

.SH NAME
mpi_omp_hello \- Simple "Hello, World!"-style hybrid MPI/OpenMP program

.SH DESCRIPTION
mpi_omp_hello is a simple "Hello, World!"-style hybrid MPI/OpenMP program.
Each thread prints a line with its MPI rank, OpenMP thread number, the core
number and the node name the thread is running on.
The output is sorted according to the MPI rank and OpenMP thread number
within each MPI rank.

The number of threads per rank can be set through the OMP_NUM_THREADS
environment variable, and the MPI processes should be started using
mpirun with the appropriate options for your environment.

.SH SEE ALSO
omp_hello(1), mpi_hello(1), hybrid_hello(1), vsc-tutorial(1)

.SH AUTHOR
Kurt Lust (Kurt.Lust@uantwerpen.be)
