.\" Written by Kurt Lust, kurt.lust@uantwerpen.be.
.TH man 1 "4 January 2022" "1.9" "serial_hello (vsc-tutorial) command"

.SH NAME
serial_hello \- Simple "Hello, World!"-style serial program

.SH DESCRIPTION
\fBserial_hello\fR is a simple "Hello, World!"-style serial program. It
prints a line with the virtual core and host it is running on.

.SH SEE ALSO
omp_hello(1), mpi_hello(1), mpi_omp_hello(1), serial_check(1), omp_check(1), mpi_check(1), mpi_omp_check(1), vsc-tutorial(1)

.SH AUTHOR
Kurt Lust (Kurt.Lust@uantwerpen.be)
