.\" Written by Kurt Lust, kurt.lust@uantwerpen.be.
.TH man 1 "20 February 2018" "1.0" "vsc-tutorial overview"

.SH NAME
vsc-tutorial \- Various example programs for the hands-on tutorials at
UAntwerp. 

.SH DESCRIPTION
vsc-tutorial contains various small programs that are used in the HPC hands-on
tutorials at UAntwerp, e.g., to start various types of programs.

Commands:
.IP \[bu] 2
omp_hello: Simple program to test starting an OpenMP program
.IP \[bu]
mpi_hello: Simple program to test starting a MPI program
.IP \[bu]
mpi_omp_hello: Simple program to test starting a hybrid MPI/OpenMP program
.IP \[bu]
eat_mem: Single-threaded program that consumes a given amount of memory to test
memory allocations

.SH SEE ALSO
omp_hello(1), mpi_hello(1), mpi_omp_hello(1), eat_mem(1)

.SH AUTHOR
Kurt Lust (Kurt.Lust@uantwerpen.be)
